import logging
import queue
import threading

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
PORT = "/dev/ttyTHS1"
BAUD = 460800
MAX_PACKET_SIZE = 609
TIMEOUT = (MAX_PACKET_SIZE * ( 8 + 2 )) / BAUD  # timeout to drop a packet reconstruction. Max packet size plus some margin

logging.basicConfig(
    level=logging.DEBUG,
    format="%(asctime)s [%(threadName)s] %(levelname)s: %(message)s",
)
log = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Shared queues
# ---------------------------------------------------------------------------
tx_queue: queue.Queue[bytes] = queue.Queue()  # bytes ready to send
rx_queue: queue.Queue[bytes] = queue.Queue()  # raw packets to process
experiment_queue: queue.Queue[dict] = queue.Queue()  # experiment requests


# this will contain the latest files generated by the experiment
# during download state, it will send all of this files to the mainboard
experiment_file_list = []  # these will contain the latests file generated by the experiment



# ACK synchronization primitives shared across threads
create_transaction_ack_event = threading.Event()
init_transaction_ack_event = threading.Event()
update_last_batch_event = threading.Event()
update_last_batch_lock = threading.Lock()
update_last_batch_shared = {
    "data": None,          # Expected: {"tid": int, "seq_offset": int, "MSB": int, "LSB": int}
    "overrun_count": 0,    # Number of times producer overwrote before consumer processed
}


# ---------------------------------------------------------------------------
# Payload state management
# ---------------------------------------------------------------------------

class PayloadState:
    """Payload state enumeration."""

    IDLE = 0
    CAPTURING = 1
    RUNNING = 2
    TURNING_ON = 3
    DOWNSCALING = 4
    PREFILTERING = 5
    INFERENCE = 9
    DOWNLOAD = 6
    OFF = 7
    FAIL = 8


class StateManager:
    """Thread-safe manager for payload state."""

    def __init__(self, initial_state: int = PayloadState.IDLE):
        self._lock = threading.Lock()
        self._state = initial_state

    def get(self) -> int:
        """Get current state."""
        with self._lock:
            return self._state

    def set(self, state: int) -> None:
        """Set current state."""
        with self._lock:
            self._state = state


# Global state manager instance
state_manager = StateManager(PayloadState.IDLE)


_inference_return_code_lock = threading.Lock()
_inference_return_code = 0


def set_inference_return_code(value: int) -> None:
    """Store latest inference process return code in a thread-safe way."""
    global _inference_return_code
    with _inference_return_code_lock:
        _inference_return_code = int(value)


def get_inference_return_code() -> int:
    """Read latest inference process return code in a thread-safe way."""
    with _inference_return_code_lock:
        return int(_inference_return_code)
